# Generated by Django 4.2.5 on 2023-09-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=254)),
                ("apellidos", models.CharField(max_length=255)),
                ("celular", models.BigIntegerField()),
                ("email", models.CharField(max_length=254)),
                ("direccion", models.CharField(max_length=254)),
                ("contrasena", models.CharField(max_length=2505)),
                ("estado", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
    ]
