# Generated by Django 4.2.5 on 2023-09-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=254)),
                ("apellidos", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=254)),
                ("celular", models.BigIntegerField()),
                ("genero", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "administrador",
                "managed": False,
            },
        ),
    ]
