# Generated by Django 4.2.7 on 2023-12-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_productos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductosRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=250, null=True)),
                ("precio", models.IntegerField(blank=True, null=True)),
                ("create_at", models.DateTimeField(blank=True, null=True)),
                ("cantidad", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "productos_registro",
                "managed": False,
            },
        ),
    ]
