# Generated by Django 4.2.7 on 2023-12-02 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_productosregistro"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Productos",
        ),
    ]
